object Versions {
    const val coreKtx = "1.9.0"
    const val lifeCycleRunTimeKtx = "2.8.2"
    const val activityCompose = "1.9.0"
    const val composeBom = "2023.03.00"
    const val junit = "4.13.2"
    const val testExtJunit = "1.1.5"
    const val espressoCore = "3.5.1"
    const val appCompat = "1.7.0"
    const val material = "1.12.0"
    const val hiltVersion = "2.51.1"
    const val hiltNavigationCompose = "1.2.0"
    const val retrofit = "2.11.0"
    const val gson = "2.10.1"
    const val moshi = "1.15.1"
    const val moshiConverter = "2.11.0"
    const val logginInterceptor = "4.12.0"
    const val coroutines = "1.3.9"

}